export const mockTasks = [
    {
      id: 1,
      title: "Создать дизайн",
      description: "Нарисовать макеты в Figma",
      priority: "medium",
      dueDate: "2025-05-12",
      complited: false,
    },
    {
      id: 2,
      title: "Написать API",
      description: "Реализовать бэкенд на Node.js",
      priority: "high",
      dueDate: "2025-05-15",
      complited: false,
    },
    {
      id: 3,
      title: "Договориться о встрече",
      description: "Выбрать дату и время встречи",
      priority: "Low",
      dueDate: "2025-05-13",
      complited: false,
    },
    {
      id: 4,
      title: "Провести собеседование",
      description: "Проверить знания кандидатов",
      priority: "high",
      dueDate: "2025-05-18",
      complited: false,
    },
    {
      id: 5,
      title: "Исправить баг",
      description: "Выяснить почему ломается проект и пофиксить",
      priority: "high",
      dueDate: "2025-05-12",
      complited: false,
    },
    {
      id: 6,
      title: "Сделать тестовое",
      description: "Придумать набор задач для тестового задания",
      priority: "Low",
      dueDate: "2025-05-20",
      complited: false,
    },
    {
      id: 7,
      title: "Создать дизайн 2",
      description: "Нарисовать макеты в Figma",
      priority: "high",
      dueDate: "2025-05-19",
      complited: false,
    },
    {
      id: 8,
      title: "Провести анализ проекта",
      description: "Изучить проект и проанализировать его",
      priority: "high",
      dueDate: "2025-05-15",
      complited: false,
    },
    {
      id: 9,
      title: "Создать дизайн 3",
      description: "Нарисовать макеты в Figma",
      priority: "high",
      dueDate: "2025-05-15",
      complited: false,
    },
    {
      id: 10,
      title: "Создать дизайн 4",
      description: "Нарисовать макеты в Figma",
      priority: "high",
      dueDate: "2025-05-18",
      complited: false,
    },
  ];